const $=id=>document.getElementById(id);
const MODEL="https://huggingface.co/YangjieOu/timesfm-3.0-onnx/resolve/main/timesfm3-fp32-c128-h64.onnx",DATA="https://huggingface.co/YangjieOu/timesfm-3.0-onnx/resolve/main/timesfm3-fp32-c128-h64.onnx.data",PATH="timesfm3-fp32-c128-h64.onnx.data";
$("modelUrl").value=MODEL;$("dataUrl").value=DATA;$("externalPath").value=PATH;ort.env.wasm.wasmPaths="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.30.0/dist/";ort.env.wasm.numThreads=1;
const now=()=>performance.now(),fmt=v=>v>=1000?`${(v/1000).toFixed(2)} s`:`${v.toFixed(1)} ms`,mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN;
function log(m,a=true){const e=$("log");e.textContent=a?e.textContent+(e.textContent?"\n":"")+m:m;e.scrollTop=e.scrollHeight}function state(k,t){const e=$("state");e.textContent=t;e.classList.remove("ok","fail","running");if(k)e.classList.add(k)}function err(e){return e instanceof Error?`${e.name}: ${e.message}\n${e.stack||""}`:String(e)}
function parse(t){const s=t.trim();try{const p=JSON.parse(s),a=Array.isArray(p)?p:p.values;if(Array.isArray(a)){const o=a.map(Number).filter(Number.isFinite);if(o.length)return o}}catch(_){}const o=s.split(/[\s,;]+/).map(Number).filter(Number.isFinite);if(!o.length)throw new Error("Serie inválida");return o}
function c128(v){return v.length>=128?v.slice(-128):new Array(128-v.length).fill(v[0]).concat(v)}
function decode(t){const d=t.dims.map(Number),a=Array.from(t.data,Number);if(d.length!==4||d[3]<9)throw new Error(`Salida inesperada [${d.join(", ")}]`);const H=d[2],nq=d[3],q10=[],q50=[],q90=[];for(let h=0;h<H;h++){const o=h*nq;q10.push(a[o]);q50.push(a[o+4]);q90.push(a[o+8])}return{dims:d,q10,q50,q90}}
function plot(values,r){const xo=Array.from({length:values.length},(_,i)=>i-values.length+1),n=Math.min(25,r.q50.length),x=Array.from({length:n},(_,i)=>i+1);Plotly.react("chart",[{x:xo,y:values,type:"scatter",mode:"lines",name:"Observado",line:{width:3}},{x,y:r.q90.slice(0,n),type:"scatter",mode:"lines",line:{width:0},showlegend:false,hoverinfo:"skip"},{x,y:r.q10.slice(0,n),type:"scatter",mode:"lines",line:{width:0},fill:"tonexty",opacity:.1,showlegend:false,hoverinfo:"skip"},{x,y:r.q50.slice(0,n),type:"scatter",mode:"lines",name:"TimesFM q50",line:{width:2.5,dash:"dot"}}],{template:"plotly_white",height:470,margin:{l:55,r:20,t:25,b:45},hovermode:"x unified",xaxis:{title:"Pasos relativos · forecast > 0"},yaxis:{title:"Valor"}},{responsive:true,displaylogo:false})}
async function detect(){if(!navigator.gpu){$("gpu").textContent="NO DISPONIBLE";return}const a=await navigator.gpu.requestAdapter({powerPreference:"high-performance"});let label="DISPONIBLE";try{const i=a.info,p=[i?.vendor,i?.architecture,i?.device,i?.description].filter(Boolean);if(p.length)label=p.join(" · ")}catch(_){}$("gpu").textContent=label}
async function demo(){const r=await fetch("./data/demo_series.json?v=5.0.0"),j=await r.json();$("series").value=JSON.stringify(j.values)}
async function run(){const b=$("runBtn");b.disabled=true;state("running","EJECUTANDO");log("",false);let s=null;try{const v=parse($("series").value),ctx=c128(v),runs=Number($("runs").value),model=$("modelUrl").value.trim(),data=$("dataUrl").value.trim(),path=$("externalPath").value.trim();log("BUILD: v5.0.0");log("ORT Web: 1.30.0");log("Bundle: ort.webgpu.min.js");log("EP: webgpu");const t0=now();s=await ort.InferenceSession.create(model,{executionProviders:["webgpu"],graphOptimizationLevel:"all",externalData:[{path,data}]});const lm=now()-t0;$("loadTime").textContent=fmt(lm);log(`✓ Session created in ${fmt(lm)}`);log(`Inputs: ${s.inputNames.join(", ")}`);log(`Outputs: ${s.outputNames.join(", ")}`);const target=new ort.Tensor("float32",Float32Array.from(ctx),[1,1,128]),times=[];let r=null;for(let i=0;i<runs;i++){const ti=now(),o=await s.run({target}),dt=now()-ti;times.push(dt);r=decode(o.forecast_quantiles??o[s.outputNames[0]]);log(`Inference ${i+1}/${runs}: ${fmt(dt)}`)}$("firstTime").textContent=fmt(times[0]);$("warmTime").textContent=fmt(mean(times.length>1?times.slice(1):times));log(`Output shape: [${r.dims.join(", ")}]`);log(`q50 first 5: ${r.q50.slice(0,5).map(x=>x.toFixed(5)).join(", ")}`);plot(v,r);state("ok","PASS")}catch(e){state("fail","FAIL");log("\nERROR\n"+err(e));console.error(e)}finally{if(s){try{await s.release()}catch(_){}}b.disabled=false}}
$("runBtn").addEventListener("click",run);$("copyBtn").addEventListener("click",async()=>navigator.clipboard.writeText($("log").textContent));await detect();await demo();